# Generated by Django 2.2.6 on 2019-10-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_system',
            name='receipt_date',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_system',
            name='receipt_greenting_text',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='book_system',
            name='receipt_no_items',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_system',
            name='receipt_publisher_address',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='book_system',
            name='receipt_publisher_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='book_system',
            name='receipt_subtotal',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_system',
            name='receipt_total',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
