# Generated by Django 2.2.6 on 2019-10-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0002_auto_20191030_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_system',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
