# Generated by Django 2.2.6 on 2019-10-30 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0004_book_owner_book_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='owner_book_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksystem.Book_System'),
        ),
    ]
