# Generated by Django 2.2.6 on 2019-10-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0008_receipt_owner_book_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_system',
            name='all_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book_system',
            name='todays_total',
            field=models.IntegerField(default=0),
        ),
    ]
