# Generated by Django 2.2.6 on 2019-10-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0009_auto_20191031_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_system',
            old_name='all_total',
            new_name='booksystem_total',
        ),
        migrations.RemoveField(
            model_name='book_system',
            name='todays_total',
        ),
    ]
