# Generated by Django 2.2.6 on 2019-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0010_auto_20191031_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_system',
            name='booksystem_today_total',
            field=models.IntegerField(default=0),
        ),
    ]
