# Generated by Django 2.2.6 on 2019-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0011_book_system_booksystem_today_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_system',
            name='booksystem_drawer_total',
            field=models.IntegerField(default=0),
        ),
    ]
