# Generated by Django 2.2.6 on 2019-10-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksystem', '0012_book_system_booksystem_drawer_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_total', models.IntegerField()),
                ('ended_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
